# template to save a list of installed packages to an artifact
# in order to reuse it at a later point.

parameters:
  condaEnv:
  envInfoDirectory: environmentInfo
  envInfoArtifact:
  envInfoFileBase:

  
steps:
  - bash: mkdir ${{parameters.envInfoDirectory}}
    displayName: Create directory for environment info

  - bash: |
        source activate ${{parameters.condaEnv}}
        pip freeze --all > ${{parameters.envInfoFileBase}}-pip.txt
        conda list > ${{parameters.envInfoFileBase}}-conda.txt
    displayName: "Gather environment information"
    workingDirectory: '$(System.DefaultWorkingDirectory)/${{parameters.envInfoDirectory}}'

  - task: PublishPipelineArtifact@1
    displayName: "Publish environment info to artifact ${{parameters.envInfoArtifact}}"
    inputs:
      path: '$(System.DefaultWorkingDirectory)/${{parameters.envInfoDirectory}}'
      artifact: ${{parameters.envInfoArtifact}}